### ISSUE TITLE
Compiled Code Doesn't Operate Successfully on Windows 11

### ISSUE THREAD

**Issue by gwillcox-r7** [klinix5/WindowsMDMLPE#1]
Trying to compile this code both in Debug and Release modes on Windows 11 will result in an EXE that runs, however it will not return any error message nor will it elevate to system. The provided EXE works fine however which raises questions as to what discrepancies there are between the code the EXE was compiled with and the provided source code, particularly for pentesting engagements where there is a need to know the exact code being run on client networks.

**Comment by klinix5** [comment]
Also https://youtu.be/o5PyVhj3eMw

**Comment by klinix5** [comment]
Long story why only x64 builds work.
And as I guess you were able to reproduce the issue now ?

**Comment by gwillcox-r7** [comment]
Thanks @klinix5 x86 Debug builds and runs fine on Windows 11 👍  Will close out this issue now as its been resolved, apologies for the confusion. As for last comment did you mean to say x86 vs x64?
